/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.component.milo.client.springboot;

import org.apache.camel.component.milo.client.MiloClientConfiguration;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * This is an Apache Camel adapter for OPC UA based on the implementation of
 * Eclipse Milo\u2122.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "camel.component.milo-client")
public class MiloClientComponentConfiguration {

    /**
     * All default options for client
     */
    private MiloClientConfiguration defaultConfiguration;
    /**
     * Default application name
     */
    private String applicationName;
    /**
     * Default application URI
     */
    private String applicationUri;
    /**
     * Default product URI
     */
    private String productUri;
    /**
     * Default reconnect timeout
     */
    private Long reconnectTimeout;

    public MiloClientConfiguration getDefaultConfiguration() {
        return defaultConfiguration;
    }

    public void setDefaultConfiguration(
            MiloClientConfiguration defaultConfiguration) {
        this.defaultConfiguration = defaultConfiguration;
    }

    public String getApplicationName() {
        return applicationName;
    }

    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    public String getApplicationUri() {
        return applicationUri;
    }

    public void setApplicationUri(String applicationUri) {
        this.applicationUri = applicationUri;
    }

    public String getProductUri() {
        return productUri;
    }

    public void setProductUri(String productUri) {
        this.productUri = productUri;
    }

    public Long getReconnectTimeout() {
        return reconnectTimeout;
    }

    public void setReconnectTimeout(Long reconnectTimeout) {
        this.reconnectTimeout = reconnectTimeout;
    }
}